---
samba_enabled: false
samba_workgroup: WORKGROUP
samba_packages:
  - samba
  - samba-vfs-modules
samba_shares:
  - name: downloads
    path: /opt/github-deploy/storage/downloads
    comment: qBittorrent downloads
  - name: tv-series
    path: /opt/github-deploy/storage/content/tv-series
    comment: TV series
  - name: movies
    path: /opt/github-deploy/storage/content/movies
    comment: Movies
samba_create_user: false
samba_user: media
samba_user_uid: 1000
samba_user_gid: 1000
