mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mosquitto
  client_id: zigbee-to-mqtt
serial:
  port: /dev/ttyUSB0
  adapter: ezsp
frontend:
  enabled: true
  port: 8080
advanced:
  network_key:
    - 123
    - 98
    - 15
    - 163
    - 104
    - 116
    - 165
    - 31
    - 93
    - 208
    - 136
    - 119
    - 201
    - 27
    - 121
    - 202
device_options: {}
devices:
  '0xa4c138478d127f22':
    friendly_name: Temperature and humidity sensor
    temperature_calibration: 0
    temperature_precision: 0
    humidity_precision: 0
    humidity_calibration: 26
    homeassistant: {}
    optimistic: true
    retain: true
  '0xa4c13897898b1ac0':
    friendly_name: button
version: 4
